//! Bootstrap flow — clone bare repo, generate local.toml, initial deploy
//!
//! `nit bootstrap <url>` takes a fresh machine from zero to fully configured.

use crate::config::{FleetConfig, GitStrategy, expand_tilde};
use crate::git;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;

/// Run the bootstrap process
pub fn run_bootstrap(url: &str) -> Result<(), Box<dyn std::error::Error>> {
    let home = dirs::home_dir().expect("cannot determine home directory");
    let git_dir = git::bare_git_dir();
    let config_dir = expand_tilde("~/.config/nit");
    let local_toml_path = config_dir.join("local.toml");

    // Step 1: Clone as bare repo (or skip if already exists)
    if git_dir.exists() {
        eprintln!("nit: bare repo already exists at {}", git_dir.display());
        eprintln!("nit: pulling latest...");
        git::exec_git_with(&GitStrategy::Bare, &["pull"])?;
    } else {
        eprintln!("nit: cloning {} as bare repo...", url);
        fs::create_dir_all(git_dir.parent().unwrap())?;

        let status = Command::new("git")
            .arg("clone")
            .arg("--bare")
            .arg(url)
            .arg(&git_dir)
            .status()?;

        if !status.success() {
            return Err("git clone failed".into());
        }

        // Configure the bare repo to track the remote
        git::exec_git_with(
            &GitStrategy::Bare,
            &[
                "config",
                "remote.origin.fetch",
                "+refs/heads/*:refs/remotes/origin/*",
            ],
        )?;
    }

    // Step 2: Checkout files to $HOME (work tree)
    eprintln!("nit: checking out files to {}...", home.display());
    git::exec_git_with(&GitStrategy::Bare, &["checkout", "--force"])?;

    // Step 2a: Set master to track origin/master with merge (not rebase) semantics.
    // Without this, the first `nit update` (which calls `git pull`) fails with
    // "no tracking information" or "cannot pull with rebase: unstaged changes"
    // when the work tree has any local edits. Merge mode is more forgiving for
    // dotfiles workflow where target files routinely diverge slightly from HEAD.
    let _ = git::exec_git_with(
        &GitStrategy::Bare,
        &["branch", "--set-upstream-to=origin/master", "master"],
    );
    let _ = git::exec_git_with(
        &GitStrategy::Bare,
        &["config", "branch.master.rebase", "false"],
    );

    // Step 3: Create ~/.gitignore if it doesn't exist
    let gitignore = home.join(".gitignore");
    if !gitignore.exists() {
        eprintln!("nit: creating ~/.gitignore (blacklist strategy)...");
        fs::write(
            &gitignore,
            r#"# nit blacklist strategy: ignore everything, whitelist dotfiles
# New dotfiles (.foorc) show up as untracked — add them with nit add

# Ignore all top-level non-dot items (Downloads, Documents, Projects, ...)
/*

# Whitelist the dotfiles project hub
!dotfiles/

# Ignore known large/generated dotdirs
.cache/
.cargo/
.rustup/
.npm/
.local/share/nit/
.Trash/
"#,
        )?;
    }

    // Step 4: Determine machine name
    let fleet_toml_path = expand_tilde("~/dotfiles/fleet.toml");
    let machine_name = if local_toml_path.exists() {
        // Already bootstrapped — read existing identity
        let content = fs::read_to_string(&local_toml_path)?;
        let local: crate::config::LocalConfig = toml::from_str(&content)?;
        eprintln!("nit: using existing identity: {}", local.machine);
        local.machine
    } else {
        // Need to choose machine name
        select_machine_name(&fleet_toml_path)?
    };

    // Step 5: Generate local.toml
    fs::create_dir_all(&config_dir)?;
    if !local_toml_path.exists() {
        eprintln!("nit: generating {}...", local_toml_path.display());
        fs::write(
            &local_toml_path,
            format!(
                r#"# Generated by nit bootstrap
machine = "{}"
identity = "~/.config/nit/age-key.txt"

[git]
strategy = "bare"
"#,
                machine_name
            ),
        )?;
    }

    // Step 6: Generate age key if it doesn't exist
    let age_key_path = config_dir.join("age-key.txt");
    if !age_key_path.exists() {
        eprintln!("nit: generating age keypair...");
        generate_age_key(&age_key_path)?;
    }

    // Step 7: Run initial deploy (load config now that local.toml exists)
    eprintln!("nit: running initial deploy...");
    let config = crate::config::load_config()?;

    // Render templates
    let mappings = crate::template::discover_templates(&config);
    for mapping in &mappings {
        match crate::template::render_template(mapping, &config) {
            Ok(rendered) => {
                let target_str = mapping.target.to_string_lossy().to_string();
                let home_str = home.to_string_lossy().to_string();
                let rel = target_str
                    .strip_prefix(&home_str)
                    .unwrap_or(&target_str)
                    .trim_start_matches('/');

                // Prepend warning comment
                let with_comment =
                    if let Some(comment) = crate::template::warning_comment(&mapping.target) {
                        format!("{}\n{}", comment, rendered)
                    } else {
                        rendered.clone()
                    };

                if let Some(parent) = mapping.target.parent() {
                    let _ = fs::create_dir_all(parent);
                }
                fs::write(&mapping.target, &with_comment)?;
                crate::syncbase::write_sync_base(rel, &with_comment);
                eprintln!("  ✓ {}", rel);
            }
            Err(e) => {
                eprintln!("  ✗ {}: {}", mapping.rel_source.display(), e);
            }
        }
    }

    // Deploy secrets
    match crate::encrypt::deploy_secrets(&config) {
        Ok(results) => {
            for r in &results {
                match &r.status {
                    crate::encrypt::DeployStatus::Deployed => {
                        eprintln!("  ✓ secret: {}", r.tier);
                    }
                    crate::encrypt::DeployStatus::Skipped(reason) => {
                        eprintln!("  ⊘ secret: {} ({})", r.tier, reason);
                    }
                    crate::encrypt::DeployStatus::Error(e) => {
                        eprintln!("  ✗ secret: {} ({})", r.tier, e);
                    }
                }
            }
        }
        Err(e) => {
            eprintln!("nit: secret deployment error: {}", e);
        }
    }

    // Apply permissions
    let perm_results = crate::permissions::apply_permissions(&config);
    let perm_set = perm_results
        .iter()
        .filter(|r| r.status == crate::permissions::PermissionStatus::Set)
        .count();
    if perm_set > 0 {
        eprintln!("  ✓ {} file permissions set", perm_set);
    }

    // Run triggers
    let mut trigger_state = crate::trigger::load_trigger_state();
    let log_dir = crate::syncbase::nit_data_dir().join("logs");
    let trigger_results = crate::trigger::run_applicable_triggers(
        &config,
        &mut trigger_state,
        &[],   // no drifted files on fresh bootstrap
        false, // not safe mode
        &log_dir,
    );
    crate::trigger::save_trigger_state(&trigger_state);
    for r in &trigger_results {
        match &r.status {
            crate::trigger::RunStatus::Success => {
                eprintln!("  ✓ trigger: {}", r.name);
            }
            crate::trigger::RunStatus::Failed(code) => {
                eprintln!("  ✗ trigger: {} (exit {})", r.name, code);
            }
            crate::trigger::RunStatus::Skipped(reason) => {
                eprintln!("  ⊘ trigger: {} ({})", r.name, reason);
            }
        }
    }

    eprintln!("\nnit: bootstrap complete for '{}'", machine_name);
    eprintln!("nit: run `nit status` to verify");

    Ok(())
}

/// Prompt the user to select a machine name from fleet.toml
fn select_machine_name(fleet_path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    if !fleet_path.exists() {
        // No fleet.toml yet — use hostname as default
        let hostname = hostname::get()
            .map(|h| h.to_string_lossy().to_string())
            .unwrap_or_else(|_| "unknown".to_string());
        eprintln!("nit: no fleet.toml found, using hostname: {}", hostname);
        return Ok(hostname);
    }

    let content = fs::read_to_string(fleet_path)?;
    let fleet: FleetConfig = toml::from_str(&content)?;

    if fleet.machines.is_empty() {
        return Err("fleet.toml has no machines defined".into());
    }

    // List available machines
    eprintln!("\nnit: available machines in fleet.toml:");
    let mut names: Vec<&String> = fleet.machines.keys().collect();
    names.sort();
    for (i, name) in names.iter().enumerate() {
        let config = &fleet.machines[*name];
        eprintln!("  {}: {} ({})", i + 1, name, config.role.join(", "));
    }

    // For non-interactive use (agents), use the hostname to auto-select
    let hostname = hostname::get()
        .map(|h| h.to_string_lossy().to_string())
        .unwrap_or_default();

    // Try exact match first
    if fleet.machines.contains_key(&hostname) {
        eprintln!("nit: auto-selected '{}' (matches hostname)", hostname);
        return Ok(hostname);
    }

    // Try case-insensitive or partial match
    for name in fleet.machines.keys() {
        if hostname.to_lowercase().contains(&name.to_lowercase())
            || name.to_lowercase().contains(&hostname.to_lowercase())
        {
            eprintln!(
                "nit: auto-selected '{}' (matches hostname '{}')",
                name, hostname
            );
            return Ok(name.clone());
        }
    }

    // Can't auto-select — print instructions and fail
    Err(format!(
        "cannot auto-select machine for hostname '{}'. Set machine name in ~/.config/nit/local.toml:\n  machine = \"<name>\"",
        hostname
    )
    .into())
}

/// Generate an age keypair and write to file
fn generate_age_key(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    use age::secrecy::ExposeSecret;

    let key = age::x25519::Identity::generate();
    let pubkey = key.to_public().to_string();
    let secret = key.to_string();

    let content = format!(
        "# created: {}\n# public key: {}\n{}\n",
        chrono::Utc::now().to_rfc3339(),
        pubkey,
        secret.expose_secret()
    );

    fs::write(path, &content)?;
    fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))?;

    eprintln!("nit: age public key: {}", pubkey);
    eprintln!("nit: add this key to fleet.toml recipients, then run `nit rekey`");

    Ok(())
}
